version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - DEBUG=${DEBUG}
        - CREDENTIALS_PATH=${CREDENTIALS_PATH}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - CREDENTIALS_PATH=${CREDENTIALS_PATH}
    env_file:
      - .env