version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - DEBUG=1  # デフォルトはデバッグモード有効
      - PORT=8000 # ポート番号
      #- FRONTEND_PATH=/app/frontend/dist
      #- GOOGLE_APPLICATION_CREDENTIALS=/app/backend/config/firebase_credential.json
