[project]
name = "googlerun-react-chatsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gitingest",
]

[tool.uv.sources]
gitingest = { path = "../gitingest" }
